### PR TITLE
Update strings.po ukr

### PR DESCRIPTION
**Pull request by alebastrov**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Translation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alebastrov** [comment]
please review Ukranian language changes

**Comment by elgatito** [comment]
@alebastrov Do you plan to complete translation? Or should I close this PR?

**Comment by jfhautenauven** [comment]
@elgatito : reject PR ? It contains nothing relevant :)

**Comment by antonsoroko** [comment]
@elgatito I think this can be closed. It was not updated for a almost a year.

**Pull request closed without merging**
