### PR TITLE
Option: If there is no localized artwork, then use English ones.

### PR DESCRIPTION
**Pull request by antonsoroko**
## Description

New option: If there is no localized artwork, then use English ones.

for https://github.com/elgatito/elementum/pull/111

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
@matke-84 @antonsoroko This complicates settings (there are already too complex).

We have primary `language` that we use for translations and secondary `language` that is used as a fallback (and if primary is not `en` then secondary is `en`).

There was always a logic to have this order for arts and translations: primary -> secondary -> original/any.

So if there is any value for `original` language and this language's art/translation exists - we can use it. 
Otherwise we can take any available art/translation.

**Comment by antonsoroko** [comment]
@elgatito the idea of that new option is to allow "not to use fallback language". like if there is no localized image, then maybe user do not want to see English image.

i can remove this option and enable fallback to english by default, it just was an idea to allow more flexibility in terms of images. not sure how many users will find it useful.

btw, for tmdb images we always get english as fallback, but i guess we can change this hardcoded value to [`SecondLanguage`](https://github.com/elgatito/elementum/commit/93478f5eba2ba2a01b61eae7ca26b57438ee142e#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R1143)

**Comment by elgatito** [comment]
> @elgatito the idea of this new option is to allow "not to use fallback language". like if there is no localized image, then maybe user do not want to see English image.
> 
> i can remove this option and enable fallback to english by default - so logic will be simpler. it just was an idea to allow more flexibility in terms of images. not sure how many users will find it useful.
> 
> btw, for tmdb images we always get english as fallback, but i guess we can change this hardcoded value to [`SecondLanguage`](https://github.com/elgatito/elementum/commit/93478f5eba2ba2a01b61eae7ca26b57438ee142e#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R1143) (i made a draft change for this).

For me if there is no localized image, and there is no english/secondlanguage image, then I would prefer non-languaged image and as the last resort - any image is better than nothing.

So it would be:
`config.Get().Language -> config.Get().SecondLanguage -> non-languaged -> any`.

**Comment by antonsoroko** [comment]
@elgatito 
>config.Get().Language -> non-languaged -> config.Get().SecondLanguage -> any.
the issue of this logic is that "non-languaged" means "nothing" (not set image).
there is no such things as "non-languaged" logo or landscape since they must have text - and this option was made for these 2 types.

also "any" (4th choice) is not possible, since we only get "first language", "second language", "no language" images. there is no 4th type.

what i mean: 
we either use SecondLanguage or not. that's it.

**Comment by elgatito** [comment]
> also "any" (4th choice) is not possible, since we only get "first language", "second language", "no language" images. there is no 4th type.

Ah, yes. They give only translations that we request, and not everything.

I don't like when there is no arts, even if it is in chinese/japanese/arabic. I would prefer any to nothing.

Instead of making this option, I would just change existing logic of selecting arts to this (in case it is not like that):
`config.Get().Language -> non-languaged -> config.Get().SecondLanguage`

**Comment by antonsoroko** [comment]
@elgatito looks like formatting of my last message was bad so first part of message was lost.

>config.Get().Language -> non-languaged -> config.Get().SecondLanguage

the issue of this logic is that "non-languaged" means "nothing" (not to set image) for art that must have text.
i mean: there is no such things as "non-languaged" logo or landscape since they **must** have text - and this option was made for these 2 types of art.
so for such art types we either use SecondLanguage or not (so we do not set art). 

to clarify - logo and landscape are optional arts (skins have logic to "emulate" them). also - elementum does not have them for TMDB in version 0.1.99, they will be added via PR.

so i the end: we can allow user to choose if user want to use SecondLanguage as fallback or have empty art OR we can always do fallback to SecondLanguage. the first approach is more flexible, the second - more simple.

---

jfyi: i did not mentioned poster, because for poster - TMDB by default provides poster with original language if there is no translated poster. see https://github.com/elgatito/elementum/pull/111#issuecomment-1994381877 for details.

**Comment by matke-84** [comment]
Landscape and Clearlogo is not something that uses the default Kodi skin Estuary. Landscape and Clearlogo are reserved for custom skins. Each custom skin has its own logic for displaying artworks, and it can rarely happen that a skin is left with an empty artwork. To me, this option has its purpose and I think it's ok. As a skinner, I like to have flexibility over artwork. :-)

I only thought that when we talk about posters, which don't have a fallback alternative in the form of another artwork, that when there is no poster in the native language, it should show the poster without text (no language), and if there is no such poster, then the original. And then @antonsoroko clarified some things for me so he is probably right.

To conclude, I would leave this option, I think it is useful.

**Comment by matke-84** [comment]
I forgot to say, if you both think it's better to go by default with original artwork as fallback, I also agree. Surely you know better how all this works and what is better for Elmentum. :-)

**Comment by antonsoroko** [comment]
@matke-84 @elgatito 
another thing i would take into consideration (and i forgot about that thing) is that we always do fallback to english text if there is no translated text. and TMDB website does the same.
example:
https://api.themoviedb.org/3/tv/234642?api_key=29a551a65eef108dd01b46e27eb0554a&append_to_response=images,translations&include_image_language=ru,en,null&language=ru
https://www.themoviedb.org/tv/234642

so unless we also want to change **text** logic (e.g. make option not to use english as fallback) - we probably should use same logic for images (always do fallback) - thus we will have consistent logic for everything.

**Comment by elgatito** [comment]
@matke-84 

> I forgot to say, if you both think it's better to go by default with original artwork as fallback, I also agree. Surely you know better how all this works and what is better for Elmentum. :-)

What do you mean by "original artwork"? You mean the size of arts? 
This issue is about selecting language-specific arts.

**Comment by elgatito** [comment]
@antonsoroko 

> the issue of this logic is that "non-languaged" means "nothing" (not to set image) for art that must have text.
i mean: there is no such things as "non-languaged" logo or landscape since they must have text - and this option was made for these 2 types of art specifically.

By non-languaged, I mean arts that are returned from TMDB with "null" for language field. Does not matter why, because it does not have texts or user set it wrong.

Again, I would not add such option to settings. 
For me, having any-language image is better than not having image at all.

I would only change the logic to use `SecondLanguage` as the last selection, after non-languaged.

**Comment by antonsoroko** [comment]
>What do you mean by "original artwork"? 

art in "original language" of video, i think. For posters TMDB does this automatically btw, see https://developer.themoviedb.org/docs/image-languages .
for other types that must have text (logo, landscape) - we do this in our code.

anyway

>I would only change the logic to use SecondLanguage as the last selection, after non-languaged.

as i wrote before - " non-languaged" is not possible for art that must have text, it will ruin those arts. like landscape without text is not a landscape (it is fanart basically, see https://kodi.wiki/view/Artwork_types#landscape ) and if we set landscape to image w/o text - then skin will not be able to fix it (if there is no landscape: skin takes fanart and adds text or logo on top of image; for logo - skin uses text; and so on).

anyway, i will change the golang part to always use Second language as fallback for art with text. so we will have art logic that is consistent with titles/description/other_text logic.

**Comment by matke-84** [comment]
> What do you mean by "original artwork"? You mean the size of arts?

I forgot the language in the sentence (original language artwork). :-)

**Comment by matke-84** [comment]
@antonsoroko @elgatito
It seems to me that everything is ok. Visually it is better, and we also gained in terms of performance which is even more important. I think users will be satisfied with this changes. :-)
P.S. Take a look at this. https://github.com/elgatito/plugin.video.elementum/issues/1008

**Comment by antonsoroko** [comment]
@matke-84 wrong thread :-)
please copy your message here 
https://github.com/elgatito/elementum/pull/111

**Comment by matke-84** [comment]
@antonsoroko 
Haha. Moved. Thanks.

**Pull request closed without merging**
