### PR TITLE
Update strings.po all languages 

### PR DESCRIPTION
**Pull request by icarok99**
Added 

msgctxt "#30119"
msgid "Added userlist ID"
msgstr ""

msgctxt "#30120"
msgid "Removed userlist ID"
msgstr ""

### CODE REVIEW

**Comment by antonsoroko** [comment]
good catch.
it actually should be like `ID of selected userlist for X` like other similar options
https://github.com/elgatito/plugin.video.elementum/blob/335284ce9dc16c753f13608070ba1cb512481c88/resources/language/messages.pot#L1261

**Comment by antonsoroko** [comment]
also, you can update `messages.pot` (template file) and then run `scripts/xgettext_merge.sh` to update all languages.

**Comment by icarok99** [comment]
> good catch. it actually should be like `ID of selected userlist for X` like other similar options
> 
> https://github.com/elgatito/plugin.video.elementum/blob/335284ce9dc16c753f13608070ba1cb512481c88/resources/language/messages.pot#L1261

The text I added is something else.
Screenshot_2024-01-16-17-26-12-165_org xbmc kodi

**Comment by antonsoroko** [comment]
@icarok99 

>The text I added is something else.

those are "debug" messages - that's why they were hardcoded. 
"Selected userlist for movies" will show name of selected userlist. and "userlist ID" will show ID (quite obvious) of selected userlist. Try to change "Userlist for movies" to see how it works.
maybe you misunderstood me.
1. those 2 "Added userlist ID" should be converted into 2 separate messages: "ID of selected userlist for movies" and "ID of selected userlist for shows".
2. "Removed userlist ID" is the same as "Added userlist ID", so new messages from step 1 should be used instead.

anyway, if you do not believe me - you always can wait for **elgatito** to answer.

**Comment by elgatito** [comment]
@icarok99 
There are two pair of Added/Removed settings, for Movies and Shows.
So if you want to make localization - then it should be either non-specific type (like it is now) and then you would use 2 localization or make 4 localizations and use all of them.

**Comment by icarok99** [comment]
@elgatito 
IMG_20240116_183146
IMG_20240116_183202

**Comment by antonsoroko** [comment]
@icarok99 please see #972 to understand what we meant. i added screenshot and links to code, so hopefully it will be more clear then text.

**Pull request closed without merging**
