### PR TITLE
allow_kodi_change_artworks_non_library setting

### PR DESCRIPTION
**Pull request by antonsoroko**
## Description

for https://github.com/elgatito/plugin.video.elementum/issues/738

## Related Issue

depends on https://github.com/elgatito/elementum/pull/69

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
Do we need this with the latest commits in elementum repo?

**Comment by antonsoroko** [comment]
No. I converted it to draft while I waited for decision about main PR.

**Comment by antonsoroko** [comment]
for https://github.com/elgatito/plugin.video.elementum/issues/795

depends on https://github.com/elgatito/elementum/pull/71

**Comment by antonsoroko** [comment]
close in favor of https://github.com/elgatito/elementum/pull/74

**Pull request closed without merging**
