### PR TITLE
Fix internal_dns_help label

### PR DESCRIPTION
**Pull request by galeksandrp**
You actually need to enable internal_dns_enabled to resolve via proxy
it is clear even from setting name (internal, e.g. system independent)

### CODE REVIEW

**Comment by antonsoroko** [comment]
So, what is the final decision?

**Comment by galeksandrp** [comment]
Changing `internal_dns_enabled` makes no difference, when proxy is enabled in settings hostnames always resolve via proxy.

So I really does not understand what `internal_dns_enabled` setting does.

PR is false assumption.

**Comment by antonsoroko** [comment]
In code I can see this:
https://github.com/elgatito/elementum/blob/d45d020335b7e46e7ed2597e84f0e3b593916bcd/proxy/proxy.go#L148
https://github.com/elgatito/elementum/blob/d45d020335b7e46e7ed2597e84f0e3b593916bcd/proxy/client.go#L71
https://github.com/elgatito/elementum/blob/d45d020335b7e46e7ed2597e84f0e3b593916bcd/proxy/client.go#L27
https://github.com/elgatito/elementum/blob/d45d020335b7e46e7ed2597e84f0e3b593916bcd/proxy/client.go#L99

but honestly I do not understand the idea behind this code.

maybe @elgatito can provide more details.

**Comment by antonsoroko** [comment]
i guess the main thing is
https://github.com/elgatito/elementum/blob/8f00b4089e0ede0656ee68525fbcde930a90043c/proxy/dns.go#L57
which will use DNS over HTTP instead of system's DNS
https://github.com/elgatito/elementum/blob/8f00b4089e0ede0656ee68525fbcde930a90043c/proxy/dns.go#L46

and if proxy is used DNS traffic will go through the proxy anyway - the question is what DNS servers will be used.
with internal_dns_enabled it should be DoH, without - not sure.

**Comment by galeksandrp** [comment]
This is WIndows, I use router's DNS server (classic UDP 53).

Thanks for the analysis, looks like even when `"Internal DNS"` is fails to resolve, `Elementum` does not stop connection - unresolved hostname just dropped to `golang`'s `net.Dial` as is, and looks like [`net.Dial` uses socks5h variant of socks, which resolves on proxy side](https://golang.org/pkg/net/http/#Transport).

https://github.com/elgatito/elementum/blob/8f00b4089e/proxy/client.go#L95
https://github.com/elgatito/elementum/blob/8f00b4089e/proxy/client.go#L122

This explains why `Elementum` can resolve `.onion` domains via proxy indifferent to `internal_dns_enabled` setting value.

**Comment by antonsoroko** [comment]
Nice. Glad to help.
But I guess the description in settings should be changed anyway, to something more clear/precise.

**Comment by antonsoroko** [comment]
Nice. Glad to help.
But I guess the description in settings should be changed anyway, to something more clear/precise.
e.g.
"Use internal DNS resolver" => "Use elementum's DNS resolver"
"Turn off if you use Tor addresses, or you want to pass resolve to local network settings" => "Turn off if you use Tor addresses, or you want to use DNS settings from OS"

**Comment by antonsoroko** [comment]
@elgatito would it make sense to rename 
"Use internal DNS resolver" => "Use elementum's DNS resolver"
"Turn off if you use Tor addresses, or you want to pass resolve to local network settings" => "Turn off if you use Tor addresses, or you want to use DNS settings from OS"

?

**Comment by elgatito** [comment]
@antonsoroko Look fine to change few labels.

**Comment by antonsoroko** [comment]
cool, updated here https://github.com/elgatito/plugin.video.elementum/pull/744

**Pull request closed without merging**
