### PR TITLE
Fix profile path for android - use non-temporary directory

### LINKED ISSUE #979: After Kodi update on android - internal data of elementum is gone
## Current Behavior

After this https://github.com/elgatito/plugin.video.elementum/commit/c4869e6455330cbabb668c650e889d4042b491e1#diff-71ebf61bf8dc7b8a527700b3aaf2c64e628b2074cd503d890e1c005a311776b5R99-R100
elementum started to store internal databases inside kodi's apk dir - `/data/user/0/org.xbmc.kodi/cache/apk/assets/` and after kodi update this dir is erased thus elementum's data like history, cache and etc is gone.

also, there is not way to edit `libtorrent.config` since that dir is not accessible by user.
the same for `elementum.log` - user can not read it.

## Possible Solution

remove those 2 lines - i tested w/o them - all good.
no idea why the were added.

## Steps to Reproduce (for bugs)

1. install kodi + elementum on android (tv)
2. update kodi version, e.g. 20.2 -> 20.3
3. see history of torrents for example - gone
4. try to open dir with databases to make backup - my android does not allow that.

## Your Environment

* Version used: 0.1.99

* Environment name and version: kodi 20.3

* Operating System and version: android tv 10

* Link to Kodi debug log:

```
[plugin.video.elementum]     Profile: "/data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum",

[plugin.video.elementum] INFO  config       ▶ Reload           [0mSetting custom profile path to: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum
[plugin.video.elementum] INFO  config       ▶ Reload           [0mCreating libtorrent.config to further usage at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/libtorrent.config

[plugin.video.elementum] INFO  database     ▶ func1            [0mDatabase backup saved at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/cache-backup.db
[plugin.video.elementum] INFO  database     ▶ func1            [0mDatabase backup saved at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/storm-backup.db
```

### PR DESCRIPTION
**Pull request by antonsoroko**
## Description

After this https://github.com/elgatito/plugin.video.elementum/commit/c4869e6455330cbabb668c650e889d4042b491e1#diff-71ebf61bf8dc7b8a527700b3aaf2c64e628b2074cd503d890e1c005a311776b5R99-R100
elementum started to store internal databases inside kodi's apk dir - `/data/user/0/org.xbmc.kodi/cache/apk/assets/` and after kodi update this dir is erased thus elementum's data like history, cache and etc is gone.

also, there is not way to edit `libtorrent.config` since that dir is not accessible by user.
the same for `elementum.log` - user can not read it.

before
```
[plugin.video.elementum]     Profile: "/data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum",

[plugin.video.elementum] INFO  config       ▶ Reload           [0mSetting custom profile path to: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum
[plugin.video.elementum] INFO  config       ▶ Reload           [0mCreating libtorrent.config to further usage at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/libtorrent.config

[plugin.video.elementum] INFO  database     ▶ func1            [0mDatabase backup saved at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/cache-backup.db
[plugin.video.elementum] INFO  database     ▶ func1            [0mDatabase backup saved at: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/storm-backup.db
```
after:
```
[plugin.video.elementum]     Profile: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/",
```

all data is browseable and readable now.

also log file was inaccessible. 
```
$ adb shell
KM6:/ $ cat /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/elementum.log
cat: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/elementum.log: Permission denied
```

## Related Issue

fixes #979

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
You just removed use of custom profile folder, that was determined by `daemon.py`.

The idea was that not always `/storage/emulated/0` was not always writable by Elementum, so it was checking what path is available. 

We basically have now 3 possible folder and try them one by one is previous does not work and is not writable:

```python

        xbmc_bin = translatePath("special://xbmcbin/")
        xbmc_data_path = xbmc_bin

        if not os.path.exists(xbmc_data_path) or not is_writable(xbmc_data_path):
            app_id = android_get_current_appid()
            log.info("%s path does not exist, so using %s as xbmc_data_path" % (xbmc_data_path, os.path.join("/data", "data", app_id)))
            xbmc_data_path = os.path.join("/data", "data", app_id)

        if not os.path.exists(xbmc_data_path):
            log.info("%s path does not exist, so using %s as xbmc_data_path" % (xbmc_data_path, translatePath("special://masterprofile/")))
            xbmc_data_path = translatePath("special://masterprofile/")

```

Correct way to fix this is to review order or those folders and try first to use the ones that are not removed on App re-installation.

**Comment by antonsoroko** [comment]
@elgatito i see. although i use android devices heavily with different versions but i have not seen a situation when `special://masterprofile/` (aka `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata`) is not writable.

so then i propose to prefer `special://masterprofile/` over `special://xbmcbin/`. i mean we try to use masterprofile first and other 2 paths.

**Comment by antonsoroko** [comment]
@elgatito 
or we can use separate paths for `dest_binary_dir` (where we keep binaries) and for `custom_path` (which is actually profile path, where we keep databases and etc).

which option is better in your opinion? same dir or different dirs?

**Comment by antonsoroko** [comment]
@elgatito 
So I tried to make profile path (aka `custom_path`) the same for all platforms if possible (addon specific path that is provided by Kodi).
Log file for shared library i also tried to make the same.
But for `dest_binary_dir` we should try to use `special://xbmcbin/` first, because `/storage/emulated` is mounted with `noexec` on all my devices.

Код получился менее красивым чем хотелось бы, но это из-за того, что для андроида dest_binary_dir должет быть одним, а custom_path другим, как я описал выше. Проверил на своих устройствах - вроде теперь всё "правильно".

Android tv 10 with shared library:

```
Binary detection: [ Source: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm/elementum, 
Destination: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/bin/android_arm/elementum ]
```
```
Profile: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/",
```
```
elementumd: loading shared library from /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/bin/android_arm/elementum.so
Preparing start with args ' -remotePort=65221 -localPort=65220 -profilePath=/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/' and log path: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/elementum.log
```

Android tv 9 with binary:

```
Binary detection: [ Source: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/bin/android_arm/elementum, 
Destination: /data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/bin/android_arm/elementum ]
```
```
Profile: "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.elementum/",
```
```
elementumd: start args: ['/data/user/0/org.xbmc.kodi/cache/apk/assets/files/plugin.video.elementum/bin/android_arm/elementum', '-remotePort=65221', '-localPort=65220']
```

---

кстати про `"/storage/emulated/legacy"` - судя по инфе из интернета это нужно было для android<6. сейчас такого пути уже нет, у меня по крайней мере.

**Comment by elgatito** [comment]
@antonsoroko I pushed changes to `daemon.py` to have separate logic between binary and data folder detection.

Binary does not need premanent folder, but the folder that can run binaries (or libraries).
While data folder is preferred to be permanent.
Also added a logic to migrate user data between folders (so that on addon update users won't loose userdata stored somewhere else).

**Comment by antonsoroko** [comment]
@elgatito looks good, my test is here - https://github.com/elgatito/plugin.video.elementum/issues/979#issuecomment-1948307316

**Pull request closed without merging**
