### PR TITLE
Added multiselect + start/stop for the session

### PR DESCRIPTION
**Pull request by Dim0N22**
Added multiselect + start/stop for the session.

### Multiselect
It is now possible to select multiple torrents by holding `Ctrl` while clicking on a torrent row. Selected torrents can be deleted together.

#### Screenshots: 
Multiple selected torrents:
image

Delete torrents modal:
image

### Session start/pause
Added buttons to start/pause session (all torrents).

#### Screenshots:
image

## Motivation and Context
@antonsoroko asked for this.

## How Has This Been Tested?
Tested on PC + mobile.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by antonsoroko** [comment]
thank you!
it works good.

the only strange change i noticed is that now when you click on torrent second time ui will not close info panel, like it was before.
is it intentional?

also i have a question/idea: would it be possible to make table "sortable"? like by size or ratio.
would you be interested in implementing such feature? :-)

**Comment by Dim0N22** [comment]
> the only strange change i noticed is that now when you click on torrent second time ui will not close info panel, like it was before.
is it intentional?

It isn't. Thanks, fixed. 

> also i have a question/idea: would it be possible to make table "sortable"? like by size or ratio.

I've pushed some commits that add basic sorting by `Name`, `Size`, `Seed ratio`, `Download rate` and `Active seeds` (in respective columns).
Please note, that due to not having non-formatted data, sorting by size works incorrectly in some cases like this:
image

I sort by the `size` field but as it's preprocessed, I can't effectively compare KB to MB and GB and so on. To fix this I need to get bytes size from the backend.

**Comment by antonsoroko** [comment]
cool, thank you.
btw, how sorting is done for Seed ratio, Download rate and Active seeds? since they have 2 columns inside.
also Size has embedded status - so no sort for status.
maybe it would make sense to somehow make sort for each column? (like add more columns headers)

**Comment by antonsoroko** [comment]
@elgatito 
btw, is there a reason why elementum uses `humanize.Bytes` instead of `humanize.IBytes`?
i mean
```
// Bytes produces a human readable representation of an SI size.
//
// See also: ParseBytes.
//
// Bytes(82854982) -> 83 MB
```
vs
```
// IBytes produces a human readable representation of an IEC size.
//
// See also: ParseBytes.
//
// IBytes(82854982) -> 79 MiB
```

would it make sense to change all Bytes to IBytes?

**Comment by elgatito** [comment]
@antonsoroko I don't like "MiB" labels. 1024 vs 1000 is not so important in Elementum for me.

**Comment by antonsoroko** [comment]
>Also it would be helpful to add creation_date or any other field that is used to order torrents returned from /torrents/list.

it is actually sorted by *.torrent files modification time:
https://github.com/elgatito/elementum/blob/b202237f078a07557f2f11c42eb6cffa89f6987a/bittorrent/service.go#L1125

not sure yet how to pass this info to api.

**Comment by elgatito** [comment]
@Dim0N22 @antonsoroko List of torrents is always returned sorted by exact order of adding to libtorrent.

**Comment by Dim0N22** [comment]
I understand. The problem is that there is no way of returning back to the default order after sorting the torrents as there is no "add_date" or at least sequential id returned from the api.

Let's say I sorted the torrents by size. Then I want to disable the sorting and return back to the default order. There is no easy way of doing it.

**Comment by antonsoroko** [comment]
@elgatito in a PR i basically take "torrent file modification time" (which is used to sort torrents before adding them to libtorrent) and just expose it. not sure what is wrong with this.

**Comment by elgatito** [comment]
@Dim0N22 I have approved `added_time` column in torrents list. If you can test with the latest elementum code, then we can include all changes in the next release.

**Comment by antonsoroko** [comment]
also `size_bytes` is available now.

i am still curious about
https://github.com/elgatito/plugin.video.elementum/pull/754#issuecomment-844974567

:-)

**Comment by Dim0N22** [comment]
> @Dim0N22 I have approved added_time column in torrents list. If you can test with the latest elementum code, then we can include all changes in the next release.

Thanks, updated sorting order.

> also size_bytes is available now.

Thanks, fixed sorting by size.

> btw, how sorting is done for Seed ratio, Download rate and Active seeds? since they have 2 columns inside.

I've mentioned that
>I've pushed some commits that add basic sorting by Name, Size, Seed ratio, Download rate and Active seeds (in respective columns).

In short this means that column containing multiple values are sorted by the first one in the column.

> also Size values have embedded status - so no sort for status.
maybe it would make sense to somehow make sort for each column? (like add more columns headers)

Unfortunately having multiple columns looks bad on mobile. Maybe one day we'll rewrite current table to a custom one so that it looks good both on mobile and desktop, but not in this PR.

Overall, I think this PR is ready for review and merge.

**Comment by antonsoroko** [comment]
>Unfortunately having multiple columns looks bad on mobile. Maybe one day we'll rewrite current table to a custom one so that it looks good both on mobile and desktop, but not in this PR.

got it.

>Overall, I think this PR is ready for review and merge.

i did some quick testing - works good. thank you.

**Comment by elgatito** [comment]
Okay, merging

**Pull request merged**
