### PR TITLE
Use script.module.six instead of local copy of six.py

### PR DESCRIPTION
**Pull request by antonsoroko**
## Description

Use script.module.six instead of local copy of six.py.

Tested on clean kodi 21.

## Related Issue

maybe it will help with https://github.com/elgatito/plugin.video.elementum/issues/1034

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Translation

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elgatito** [comment]
@antonsoroko Are you sure it would help? I had no issues installing on Kodi 21, so I could not reproduce.

**Comment by antonsoroko** [comment]
@elgatito i am not sure since i do not have arch linux. but as i see they started to use python 3.12 so that might be the issue.
i tested this on linux flatpak version of kodi 21 but it uses python 3.10.

but in general, this fix should be useful at least because we do not need to update local copy of six module anymore.

**Comment by antonsoroko** [comment]
btw, i remember that some time ago i manually updated `six.py` in burst, just in case. but in burst it is a part of a local copy of urllib3, so i think it is easier to leave it as is.

but in elementum it makes sense to use script.module.six imho.

**Comment by elgatito** [comment]
@antonsoroko If possible - I would prefer having a script locally, instead of making a dependency in `addon.xml`. 
They tend to force people moving to newer version of Kodi, and I hope Elementum is still working on Kodi 17, so if that works - let's keep it as is.

**Comment by antonsoroko** [comment]
ok

**Pull request closed without merging**
